---
- name: main.yml | Include OS-specific variables
  include_vars: "vars-{{ ansible_os_family }}.yml"

- name: main.yml | Getting installed packages
  package_facts:
    manager: "auto"

- name: main.yml | MariaDB for {{ ansible_os_family }}
  include_tasks: "setup-{{ ansible_os_family }}.yml"

- name: main.yml | Configuring MariaDB
  include_tasks: "configure.yml"

- name: main.yml | Securing MariaDB
  include_tasks: "secure-installation.yml"

- name: main.yml | Modifying database(s)
  include_tasks: "database.yml"
  when: mariadb_database is defined

- name: main.yml | Modifying user(s)
  include_tasks: "user.yml"
  when: mariadb_user is defined

- name: main.yml | UFW
  include_tasks: ufw.yml
  when: "'ufw' in ansible_facts.packages"