---
- name: Converge
  hosts: all
  become: true

    - name: Converge | Install Python if not already present.
      raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
      changed_when: false

    - name: Converge | Gather facts after Python is definitely present.
      setup:

  roles:
    - role: ubzyhd.mariadb